# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Ingrid Hsu
email: ingridhsu8@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
 Computer Science and Philosophy double major at Swarthmore College interested in AI, cognitive science, and tech ethics.

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ihsu1.github.io/"
github_repo: ihsu1.github.io 
github_username:  ihsu1

# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# Optional social link, you can choose from the following options:
# twitter (default), instagram, medium, or dribbble
social_link: instagram
social_username: ingridhsu_

# Set theme color here
# Choose from: black (default), blue, gray, magenta, orange, red, white, and yellow.
theme_color: light

# Build settings
remote_theme: "broccolini/athena"
plugins:
  - jekyll-feed
markdown: kramdown

# Navigation Bar
nav:
  - title: Home
    url: /
  - title: About
    url: /about/
  - title: Contact
    url: /contact/
  - title: Education
    url: /education/
  - title: Projects
    url: /projects/
  - title: Résumé
    url: /resume/
  - title: Art
    url: /art/
    children: 
      - title: Breadth
        url: /art/breadth/
      - title: Series 1- Life Through Machines
        url: /art/series1/
      - title: Series 2- Inorganic Anatomy
        url: /art/series2/
      - title: Art Curriculum Vitae
        url: /art/art_cv/
  - title: Essays
    url: /essays/
    children:
      - title: "Brain Invaders: The Final Frontier of Surveillance Capitalism"
        url: /essays/brain_invaders/
      - title: "Shadows on the Screen: Truth, Technology, and the New Cave"
        url: /essays/shadows_on_the_screen/

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
